import crypto from 'node:crypto';
import { prisma } from '../config/prisma.js';
import { AppError } from '../utils/errors.js';
export type ResourceType='CLINICAL_CASE'|'CASE_ANALYSIS'|'SIMILAR_CASES'|'RESEARCH_COLLECTION'|'DISEASE_TREND'|'EVIDENCE_REPORT';
export type AccessType='PRIVATE'|'ORGANIZATION'|'PUBLIC';
export type Expiry='1_HOUR'|'24_HOURS'|'7_DAYS'|'30_DAYS'|'NEVER';
const expiryMs:Record<Exclude<Expiry,'NEVER'>,number>={'1_HOUR':3600000,'24_HOURS':86400000,'7_DAYS':604800000,'30_DAYS':2592000000};
const validTypes=new Set<ResourceType>(['CLINICAL_CASE','CASE_ANALYSIS','SIMILAR_CASES','RESEARCH_COLLECTION','DISEASE_TREND','EVIDENCE_REPORT']);
export async function assertResource(type:ResourceType,id:string,userId:string){if(!validTypes.has(type))throw new AppError('INVALID_RESOURCE_TYPE','Unsupported QR resource type',422);if(['CLINICAL_CASE','CASE_ANALYSIS','SIMILAR_CASES','EVIDENCE_REPORT'].includes(type)){const c=await prisma.clinicalCase.findUnique({where:{id}});if(!c)throw new AppError('RESOURCE_NOT_FOUND','Clinical case resource not found',404);if(c.userId!==userId)throw new AppError('FORBIDDEN','Only the case owner can share this resource',403);return;}if(type==='RESEARCH_COLLECTION'){if(!await prisma.researchPaper.findUnique({where:{id}}))throw new AppError('RESOURCE_NOT_FOUND','Research resource not found',404);return;}if(!await prisma.diseaseTrend.findUnique({where:{id}}))throw new AppError('RESOURCE_NOT_FOUND','Trend resource not found',404);}
export async function createQr(i:{userId:string;resourceType:ResourceType;resourceId:string;accessType:AccessType;expiresIn:Expiry;origin:string}){await assertResource(i.resourceType,i.resourceId,i.userId);const token=crypto.randomBytes(32).toString('hex');const expiresAt=i.expiresIn==='NEVER'?null:new Date(Date.now()+expiryMs[i.expiresIn]);const qr=await prisma.qrShare.create({data:{token,userId:i.userId,resourceType:i.resourceType,resourceId:i.resourceId,accessType:i.accessType,expiresAt}});return {...qr,shareUrl:`${i.origin}/share/${qr.token}`};}
export const listQr=(userId:string)=>prisma.qrShare.findMany({where:{userId},orderBy:{createdAt:'desc'}});
export async function getQr(id:string,userId:string){const qr=await prisma.qrShare.findFirst({where:{id,userId}});if(!qr)throw new AppError('QR_NOT_FOUND','QR share not found',404);return qr;}
export async function revokeQr(id:string,userId:string){await getQr(id,userId);return prisma.qrShare.update({where:{id},data:{isActive:false}});}
export async function deleteQr(id:string,userId:string){await getQr(id,userId);await prisma.qrShare.delete({where:{id}});return {deleted:true};}
async function permitted(qr:any,user:any){if(qr.accessType==='PUBLIC')return;if(!user)throw new AppError('AUTH_REQUIRED','Authentication required for this QR resource',401);if(qr.accessType==='PRIVATE'&&qr.userId!==user.id&&user.role!=='ADMIN')throw new AppError('FORBIDDEN','Access restricted to the resource owner',403);if(qr.accessType==='ORGANIZATION'&&qr.userId!==user.id&&user.role!=='ADMIN'){const [a,b]=await Promise.all([prisma.user.findUnique({where:{id:qr.userId}}),prisma.user.findUnique({where:{id:user.id}})]);if(!a||!b||a.organization!==b.organization)throw new AppError('FORBIDDEN','Access restricted to the owner organization',403);}}
async function payload(qr:any){if(['CLINICAL_CASE','CASE_ANALYSIS','SIMILAR_CASES','EVIDENCE_REPORT'].includes(qr.resourceType)){const c=await prisma.clinicalCase.findUnique({where:{id:qr.resourceId},include:{analysis:true,evidence:true}});if(!c)throw new AppError('RESOURCE_NOT_FOUND','Shared resource no longer exists',404);return {title:c.title,summary:c.analysis?.summary||'Analysis has not been generated yet.',analysis:c.analysis,evidence:c.evidence};}if(qr.resourceType==='RESEARCH_COLLECTION'){const p=await prisma.researchPaper.findUnique({where:{id:qr.resourceId}});if(!p)throw new AppError('RESOURCE_NOT_FOUND','Shared research no longer exists',404);return {title:p.title,summary:p.abstract,citation:p.citation,externalUrl:p.externalUrl};}const t=await prisma.diseaseTrend.findUnique({where:{id:qr.resourceId}});if(!t)throw new AppError('RESOURCE_NOT_FOUND','Shared trend no longer exists',404);return {title:`${t.disease} in ${t.region}`,summary:`${t.activity} activity · ${t.trend}`,trend:t};}
export async function resolveQr(token:string,user?:{id:string;role:string}){const qr=await prisma.qrShare.findUnique({where:{token}});if(!qr)throw new AppError('QR_INVALID','Invalid MedIntel QR code',404);if(!qr.isActive)throw new AppError('QR_REVOKED','This QR access link has been revoked',410);if(qr.expiresAt&&qr.expiresAt<new Date())throw new AppError('QR_EXPIRED','This QR access link has expired',410);await permitted(qr,user);const [owner,resource]=await Promise.all([prisma.user.findUnique({where:{id:qr.userId},select:{name:true,organization:true}}),payload(qr)]);await prisma.qrShare.update({where:{id:qr.id},data:{scanCount:{increment:1},lastScannedAt:new Date()}});return {id:qr.id,resourceType:qr.resourceType,title:resource.title,owner:owner?.name||'MedIntel user',accessType:qr.accessType,expiresAt:qr.expiresAt,accessGranted:true,resource};}
