/* Optional production adapter. Existing local services remain the offline fallback. */
export const API_BASE = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_API_URL) ? process.env.NEXT_PUBLIC_API_URL : '';
export type ApiResponse<T> = { success: boolean; data?: T; error?: { code: string; message: string } };
let token: string | null = typeof window !== 'undefined' ? localStorage.getItem('medintel.jwt') : null;
export const apiAuth = { setToken(value:string){token=value; if(typeof window!=='undefined') localStorage.setItem('medintel.jwt',value)}, clear(){token=null; if(typeof window!=='undefined')localStorage.removeItem('medintel.jwt')}, get(){return token} };
export async function apiRequest<T>(path:string, options:RequestInit={}) : Promise<T> { if(!API_BASE) throw new Error('API not configured'); const response=await fetch(`${API_BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}}); const body=await response.json() as ApiResponse<T>; if(!response.ok||!body.success) throw new Error(body.error?.message||'API request failed'); return body.data as T; }
export const authApi={register:(payload:unknown)=>apiRequest<{user:unknown;token:string}>('/auth/register',{method:'POST',body:JSON.stringify(payload)}).then(result=>{apiAuth.setToken(result.token);return result}),login:(payload:unknown)=>apiRequest<{user:unknown;token:string}>('/auth/login',{method:'POST',body:JSON.stringify(payload)}).then(result=>{apiAuth.setToken(result.token);return result}),me:()=>apiRequest<{user:unknown}>('/auth/me')};
export const caseApi={list:()=>apiRequest<unknown[]>('/cases'),get:(id:string)=>apiRequest<unknown>(`/cases/${id}`),create:(payload:unknown)=>apiRequest<unknown>('/cases',{method:'POST',body:JSON.stringify(payload)}),update:(id:string,payload:unknown)=>apiRequest<unknown>(`/cases/${id}`,{method:'PUT',body:JSON.stringify(payload)}),remove:(id:string)=>apiRequest<unknown>(`/cases/${id}`,{method:'DELETE'}),analyze:(id:string)=>apiRequest<unknown>(`/cases/${id}/analyze`,{method:'POST'}),similar:(id:string)=>apiRequest<unknown[]>(`/cases/${id}/similar`),evidence:(id:string)=>apiRequest<unknown[]>(`/cases/${id}/evidence`)};
export const researchApi={list:(query='')=>apiRequest<unknown[]>(`/research${query?`?${query}`:''}`),get:(id:string)=>apiRequest<unknown>(`/research/${id}`),save:(id:string)=>apiRequest<unknown>(`/research/${id}/save`,{method:'POST'}),unsave:(id:string)=>apiRequest<unknown>(`/research/${id}/save`,{method:'DELETE'}),saved:()=>apiRequest<unknown[]>('/saved-research')};
export const trendApi={list:(query='')=>apiRequest<unknown[]>(`/trends${query?`?${query}`:''}`),get:(id:string)=>apiRequest<unknown>(`/trends/${id}`),regions:()=>apiRequest<unknown[]>('/trends/regions')};
export const notificationApi={list:()=>apiRequest<unknown[]>('/notifications'),markRead:(id:string)=>apiRequest<unknown>(`/notifications/${id}/read`,{method:'PATCH'})};
