import {papers,sampleCase,similarCases,trends} from '@/data/demo';
import type {ClinicalCase,User,Analysis,ResearchPaper} from '@/types';
const key='medintel.demo.v1';
type State={cases:ClinicalCase[];saved:string[];user:User;notifications:boolean;reducedMotion:boolean};
export const defaults:State={cases:[sampleCase],saved:[],user:{name:'Dr. Alex Morgan',email:'alex@example.com',profession:'Physician',organization:'Research workspace'},notifications:true,reducedMotion:false};
export function readState():State{if(typeof window==='undefined')return defaults;try{const stored=localStorage.getItem(key);return stored?{...defaults,...JSON.parse(stored)}:defaults}catch{return defaults}}
export function writeState(update:Partial<State>){const next={...readState(),...update};localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event('medintel-change'));return next}
export const caseService={list:()=>readState().cases,get:(id:string)=>readState().cases.find(c=>c.id===id),save:(c:ClinicalCase)=>{if(!c.title.trim()||!c.symptoms.trim())throw new Error('Add a title and symptoms before saving.');const items=readState().cases;const saved={...c,updatedAt:new Date().toISOString()};writeState({cases:[saved,...items.filter(x=>x.id!==c.id)]});return saved},remove:(id:string)=>writeState({cases:readState().cases.filter(c=>c.id!==id)}),async analyze(c:ClinicalCase):Promise<Analysis>{if(!c.symptoms.trim())throw new Error('Enter symptoms to analyze your case.');const text=[c.title,c.symptoms,c.history,c.examination,c.labs,c.imaging,c.medications,c.observations].join(' ').toLowerCase();const dictionary=['fever','headache','myalgia','fatigue','rash','thrombocytopenia','dengue','ns1','covid','cough','dyspnea','breathlessness','platelet','oxygen','diabetes','hypertension'];const entities=dictionary.filter(t=>text.includes(t));const ranked=researchService.search('', 'All','All','relevance',text);return {summary:`${c.age?`${c.age}-year-old`:'Age not provided'} ${c.sex.toLowerCase()} patient. Reported symptoms: ${c.symptoms} ${c.labs?`Investigations: ${c.labs}`:''}`,entities,features:[c.history,c.examination,c.labs,c.imaging].filter(Boolean),keywords:entities,researchIds:ranked.slice(0,3).map(p=>p.id),limitations:'Demo extraction uses keyword matching and your supplied text. Related records are illustrative; this is not an AI diagnosis or a validated similarity assessment.'}}};
export const researchService={list:()=>papers,get:(id:string)=>papers.find(p=>p.id===id),search:(query:string,category='All',disease='All',sort='relevance',caseText=''):ResearchPaper[]=>papers.map(p=>({...p,relevance:caseText?Math.min(98,45+p.tags.filter(t=>caseText.includes(t)).length*10):p.relevance})).filter(p=>(category==='All'||p.category===category)&&(disease==='All'||p.disease===disease)&&`${p.title} ${p.authors} ${p.summary}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='newest'?b.date.localeCompare(a.date):sort==='oldest'?a.date.localeCompare(b.date):b.relevance-a.relevance),toggleSave:(id:string)=>{if(!papers.some(p=>p.id===id))throw new Error('Research record not found');const saved=readState().saved;writeState({saved:saved.includes(id)?saved.filter(x=>x!==id):[...saved,id]})}};
export const similarCaseService={list:(c?:ClinicalCase)=>{if(!c)return similarCases;const text=c.symptoms.toLowerCase();return similarCases.map(s=>({...s,similarity:Math.min(98,55+s.symptoms.filter(x=>text.includes(x.toLowerCase())).length*13)})).sort((a,b)=>b.similarity-a.similarity)}};
export const trendService={list:()=>trends,get:(id:string)=>trends.find(t=>t.id===id)};
export const authService={signIn:(email:string,password:string)=>{if(!email.includes('@')||password.length<8)throw new Error('Enter a valid email and a password of at least 8 characters.');sessionStorage.setItem('medintel-demo-session','true');return writeState({user:{...readState().user,email}}).user},signOut:()=>sessionStorage.removeItem('medintel-demo-session'),update:(user:User)=>writeState({user})};
export function newCase():ClinicalCase{return {id:crypto.randomUUID(),title:'',age:'',sex:'Not specified',symptoms:'',history:'',examination:'',labs:'',imaging:'',medications:'',observations:'',attachments:[],status:'Draft',updatedAt:new Date().toISOString()}}

