'use client';
import {useState,useEffect,type FormEvent} from 'react';
import Link from '@/components/link';
import {ArrowLeft,ArrowRight,Check,LogOut} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {authService,writeState} from '@/services';
import type {User} from '@/types';
import {PageHead,Picker,Brand,useData} from './shared';
export function Profile(){const data=useData();const [user,setUser]=useState<User>(data.user);const [notifications,setNotifications]=useState(data.notifications);const [motion,setMotion]=useState(data.reducedMotion);useEffect(()=>{setUser(data.user)},[data.user]);return <><PageHead eyebrow="PROFILE & PREFERENCES" title="A workspace that feels like yours." description="Your professional details and local demonstration preferences."/><div className="settings-layout"><form className="panel settings-form" onSubmit={e=>{e.preventDefault();try{authService.update(user);toast.success('Profile saved on this device')}catch{toast.error('Could not save profile')}}}><div className="profile-summary"><span className="avatar large">{user.name.split(' ').slice(-2).map(x=>x[0]).join('')}</span><div><h2>Your professional profile</h2><p>Shown within this browser’s workspace</p></div></div>{(['name','email','profession','organization'] as const).map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}<input required value={user[k]} type={k==='email'?'email':'text'} onChange={e=>setUser({...user,[k]:e.target.value})}/></label>)}<button className="btn primary">Save profile <Check size={16}/></button></form><div><div className="panel preferences"><h2>Preferences</h2><div><label htmlFor="notifications"><strong>Workspace updates</strong><span>Remember your preference for future connected notifications.</span></label><Switch id="notifications" checked={notifications} onCheckedChange={v=>{setNotifications(v);writeState({notifications:v});toast.success('Notification preference saved')}}/></div><div><label htmlFor="motion"><strong>Reduced motion</strong><span>Limit movement in this workspace.</span></label><Switch id="motion" checked={motion} onCheckedChange={v=>{setMotion(v);writeState({reducedMotion:v});document.documentElement.classList.toggle('reduce-motion',v);toast.success('Motion preference saved')}}/></div></div><div className="panel"><h3>About this workspace</h3><p className="small muted">Cases, attachments, reading lists and preferences are stored locally in this browser. There is no connected clinical AI service, cloud account or live surveillance feed.</p><button className="btn secondary" onClick={()=>{authService.signOut();location.href='/login'}}><LogOut size={16}/>Leave demo session</button></div></div></div></>}
export function Auth({signup}:{signup:boolean}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [profession,setProfession]=useState('Physician');const [organization,setOrganization]=useState('');const [error,setError]=useState('');const [google,setGoogle]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();try{authService.signIn(email,password);if(signup)authService.update({name,email,profession,organization});location.href='/dashboard'}catch(e){setError((e as Error).message)}};return <main className="auth-page"><Link href="/" className="auth-back"><ArrowLeft size={17}/>Back to MedIntel</Link><div className="auth-intro"><Brand/><h1>Bring curiosity.<br/><em>Find perspective.</em></h1><p>Clinical intelligence.<br/>Backed by evidence. Guided by you.</p></div><form className="auth-form panel" onSubmit={submit}><span className="eyebrow">YOUR CLINICAL RESEARCH COMPANION</span><h2>{signup?'Create your workspace':'Welcome back to MedIntel'}</h2><p>This demonstration opens a local session. No account is created and passwords are never stored.</p>{signup&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@organization.com" autoComplete="email"/></label><label>Demo password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" autoComplete="off"/></label>{signup&&<><label>Profession<Picker value={profession} onChange={setProfession} options={['Physician','Researcher','Medical student','Other healthcare professional']} label="Profession"/></label><label>Organization<input required value={organization} onChange={e=>setOrganization(e.target.value)}/></label></>}{error&&<p role="alert" className="error-message">{error}</p>}<button className="btn primary" type="submit">{signup?'Create demo profile':'Sign in to demo'}<ArrowRight size={17}/></button><button className="btn secondary" type="button" onClick={()=>setGoogle(true)}>Continue with Google</button><p>{signup?'Already have a demo profile?':'New to MedIntel?'} <Link className="text-link" href={signup?'/login':'/signup'}>{signup?'Sign in':'Create a profile'}</Link></p><Link href="/dashboard" className="text-link">Explore without signing in →</Link></form><Dialog open={google} onOpenChange={setGoogle}><DialogContent><DialogHeader><DialogTitle>Google sign-in is not connected</DialogTitle><DialogDescription>This demonstration has no identity provider configured. Continue with a local demo session to explore the workspace.</DialogDescription></DialogHeader><Link className="btn primary" href="/dashboard">Open demo workspace <ArrowRight size={16}/></Link></DialogContent></Dialog></main>}



