'use client';
import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {Copy,Download,ExternalLink,LockKeyhole,RefreshCw,ShieldCheck,Trash2} from 'lucide-react';
import {API_BASE} from '@/services/api';
import {qrApi,type QrShare} from '@/services/qrApi';
import Link from '@/components/link';
import {Empty} from './shared';

export function QrCenter(){
 const [items,setItems]=useState<QrShare[]>([]); const [resourceId,setResourceId]=useState('sample-001'); const [resourceType,setResourceType]=useState('CLINICAL_CASE'); const [accessType,setAccessType]=useState('PRIVATE'); const [expiresIn,setExpiresIn]=useState('24_HOURS'); const [selected,setSelected]=useState<QrShare|null>(null); const [image,setImage]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const load=()=>qrApi.list().then(setItems).catch(e=>setMessage(e.message)); useEffect(()=>{if(API_BASE)load()},[]);
 async function generate(){setBusy(true);setMessage('');try{const item=await qrApi.generate({resourceType,resourceId,accessType,expiresIn});setItems(x=>[item,...x]);setSelected(item);setImage(await QRCode.toDataURL(item.shareUrl||'',{width:360,margin:2,color:{dark:'#173c39',light:'#fbfaf6'}}));}catch(e){setMessage(e instanceof Error?e.message:'Could not generate QR')}finally{setBusy(false)}}
 async function select(item:QrShare){setSelected(item);setImage(await QRCode.toDataURL(item.shareUrl||`${location.origin}/share/${item.token}`,{width:360,margin:2,color:{dark:'#173c39',light:'#fbfaf6'}}))}
 if(!API_BASE)return <Empty title="Connect the MedIntel backend" description="QR sharing is backed by secure server tokens. Set VITE_API_URL and sign in to enable the QR Center." href="/dashboard" label="Return to overview"/>;
 return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">SECURE COLLABORATION</p><h1>QR Center</h1><p>Share clinical intelligence with a verifiable, expiring MedIntel link.</p></div><div className="soft-badge"><ShieldCheck size={15}/> Token protected</div></div>
  <div className="split-grid"><section className="panel"><div className="panel-header"><div><p className="eyebrow">CREATE ACCESS</p><h2>Generate a secure QR</h2></div><LockKeyhole size={20}/></div><label>Resource type<select value={resourceType} onChange={e=>setResourceType(e.target.value)}><option value="CLINICAL_CASE">Clinical case</option><option value="CASE_ANALYSIS">Case analysis</option><option value="EVIDENCE_REPORT">Evidence report</option><option value="RESEARCH_COLLECTION">Research item</option><option value="DISEASE_TREND">Disease trend</option></select></label><label>Resource ID<input value={resourceId} onChange={e=>setResourceId(e.target.value)} placeholder="case or resource ID"/></label><div className="form-row"><label>Access<select value={accessType} onChange={e=>setAccessType(e.target.value)}><option value="PRIVATE">Private</option><option value="ORGANIZATION">Organization</option><option value="PUBLIC">Public</option></select></label><label>Expires<select value={expiresIn} onChange={e=>setExpiresIn(e.target.value)}><option value="1_HOUR">1 hour</option><option value="24_HOURS">24 hours</option><option value="7_DAYS">7 days</option><option value="30_DAYS">30 days</option><option value="NEVER">Never</option></select></label></div><button className="primary-button" onClick={generate} disabled={busy}>{busy?'Creating…':'Generate QR code'}</button>{message&&<p className="form-message">{message}</p>}<p className="helper-text">The QR contains a random token only. Clinical content is resolved after MedIntel checks access and expiry.</p></section>
   <section className="panel qr-preview">{selected&&image?<><div className="qr-frame"><img src={image} alt="Secure MedIntel QR code"/></div><strong>{selected.resourceType.replaceAll('_',' ')}</strong><span className="muted">{selected.accessType} · {selected.expiresAt?`expires ${new Date(selected.expiresAt).toLocaleString()}`:'no expiry'}</span><div className="button-row"><a className="secondary-button" href={image} download={`medintel-${selected.id}.png`}><Download size={15}/> Download</a><button className="secondary-button" onClick={()=>navigator.clipboard?.writeText(selected.shareUrl||'')}><Copy size={15}/> Copy link</button><Link className="secondary-button" href={`/share/${selected.token}`}><ExternalLink size={15}/> Open report</Link></div></>:<div className="empty-qr"><ShieldCheck size={36}/><h3>Your generated QR appears here</h3><p>Choose an access policy and resource, then generate a token.</p></div>}</section></div>
  <section className="panel"><div className="panel-header"><div><p className="eyebrow">ACCESS HISTORY</p><h2>Active and revoked links</h2></div><button className="icon-button" onClick={load} aria-label="Refresh QR history"><RefreshCw size={16}/></button></div>{items.length===0?<p className="muted">No QR links yet.</p>:<div className="table-list">{items.map(item=><div className="table-row" key={item.id}><div><strong>{item.resourceType.replaceAll('_',' ')}</strong><small>{item.accessType} · {item.scanCount} scans · {item.isActive?'Active':'Revoked'}</small></div><div className="button-row"><button className="text-button" onClick={()=>select(item)}>View</button>{item.isActive&&<button className="text-button danger" onClick={async()=>{await qrApi.revoke(item.id);load()}}>Revoke</button>}<button className="text-button danger" onClick={async()=>{await qrApi.remove(item.id);load()}}><Trash2 size={14}/></button></div></div>)}</div>}</section>
 </div>
}
