'use client';
import {useState,useEffect} from 'react';
import Link from '@/components/link';
import {ArrowLeft,ArrowUpRight,BookOpen,Bookmark,Clipboard,Download,Search,SlidersHorizontal} from 'lucide-react';
import {toast} from 'sonner';
import {researchService} from '@/services';
import {papers} from '@/data/demo';
import type {ResearchPaper} from '@/types';
import {PageHead,Picker,Empty,useData,download} from './shared';
export function PaperCard({paper}:{paper:ResearchPaper}){const data=useData();const saved=data.saved.includes(paper.id);return <article className="paper-card"><div className="paper-top"><span className="paper-category">{paper.category}</span><button className={'icon-button '+(saved?'is-saved':'')} aria-label={(saved?'Unsave ':'Save ')+paper.title} aria-pressed={saved} onClick={()=>{try{researchService.toggleSave(paper.id);toast.success(saved?'Removed from saved research':'Added to your reading list')}catch{toast.error('Could not save research')}}}><Bookmark size={19} fill={saved?'currentColor':'none'}/></button></div><Link href={'/research/'+paper.id}><h3>{paper.title}</h3></Link><p>{paper.summary}</p><div className="paper-source"><strong>{paper.journal}</strong><span>{paper.authors}</span></div><div className="paper-bottom"><span>{new Date(paper.date+'T12:00:00').toLocaleDateString('en-GB',{month:'short',year:'numeric'})}</span><Link href={'/research/'+paper.id} className="text-link">Read research <ArrowUpRight size={15}/></Link></div><div className="relevance"><span style={{width:paper.relevance+'%'}}/></div><small className="relevance-label">{paper.relevance}% illustrative relevance</small></article>}
export function Research({savedOnly=false}:{savedOnly?:boolean}){const data=useData();const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [disease,setDisease]=useState('All');const [sort,setSort]=useState('newest');const [date,setDate]=useState('Any date');useEffect(()=>{setQuery(new URLSearchParams(location.search).get('q')||'')},[]);const results=researchService.search(query,category,disease,sort).filter(p=>(!savedOnly||data.saved.includes(p.id))&&(date==='Any date'||p.date>='2024-01-01'));return <><PageHead eyebrow={savedOnly?'YOUR PERSONAL READING ROOM':'LATEST RESEARCH / THE EVIDENCE LIBRARY'} title={savedOnly?'Keep the important ideas close.':'Make room for discovery.'} description={savedOnly?'Your saved publications, ready when you are.':'A curated collection of clinical literature and guidelines, with the original sources a click away.'}>{savedOnly&&data.saved.length>0&&<button className="btn secondary" onClick={()=>download('medintel-reading-list.json',JSON.stringify(papers.filter(p=>data.saved.includes(p.id)),null,2))}><Download size={16}/>Export reading list</button>}</PageHead><div className="library-banner"><BookOpen size={34}/><div><span className="eyebrow">EVIDENCE DESERVES CONTEXT</span><p>Read the source. Consider its date. Bring your clinical judgment.</p></div><span className="pill">Curated collection · not a live feed</span></div><div className="toolbar library-toolbar"><div className="search-box"><Search size={18}/><input aria-label="Search publications" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, authors or topics…"/></div><div className="filter-group"><Picker label="Research category" value={category} onChange={setCategory} options={['All','Guideline','Review','Clinical trial','Reference']}/><Picker label="Research disease" value={disease} onChange={setDisease} options={['All','Dengue','COVID-19']}/><Picker label="Publication date" value={date} onChange={setDate} options={['Any date','2024 onward']}/><Picker label="Sort research" value={sort} onChange={setSort} options={['newest','oldest','relevance']}/></div></div><div className="results-label"><span>{results.length} publications{savedOnly?' saved':''}</span><button className="text-link" onClick={()=>{setQuery('');setCategory('All');setDisease('All');setDate('Any date');setSort('newest')}}><SlidersHorizontal size={14}/>Reset filters</button></div><div className="research-grid">{results.map(p=><PaperCard key={p.id} paper={p}/>)}</div>{!results.length&&<Empty title={savedOnly&&!data.saved.length?'Your reading room is waiting':'No publications match these filters'} description={savedOnly&&!data.saved.length?'Save a publication using its bookmark to collect it here.':'Try a broader search or reset the filters.'} href={!data.saved.length&&savedOnly?'/research':undefined} label="Explore the library"/>}</>}
export function ResearchDetail({id}:{id:string}){const p=researchService.get(id);const data=useData();if(!p)return <Empty title="Publication not found" description="Explore the available publications in the research library." href="/research" label="Back to research"/>;const saved=data.saved.includes(id);return <><Link href="/research" className="text-link back-link"><ArrowLeft size={15}/>Back to the reading room</Link><article className="reading-page"><div className="eyebrow">{p.category.toUpperCase()} / {p.disease.toUpperCase()}</div><h1>{p.title}</h1><div className="reading-byline"><strong>{p.authors}</strong><span>{p.journal} · {new Date(p.date+'T12:00:00').toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</span></div><div className="actions"><a className="btn primary" href={p.url} target="_blank" rel="noreferrer">View original publication <ArrowUpRight size={17}/></a><button className="btn secondary" onClick={()=>{researchService.toggleSave(id);toast.success(saved?'Removed from reading list':'Saved to reading list')}}><Bookmark size={17} fill={saved?'currentColor':'none'}/>{saved?'Saved to reading list':'Save research'}</button></div><div className="reading-divider"/><section><span className="eyebrow">EDITORIAL OVERVIEW</span><h2>A starting point for closer reading.</h2><p className="reading-summary">{p.summary}</p><p className="small muted">This short overview is prepared for the demonstration library. It is not a full-text analysis or a treatment recommendation. Consult the original publication for methods, results, limitations and any later updates.</p></section><section className="citation-box"><div className="panel-title"><h3>Citation details</h3><button className="icon-button" aria-label="Copy citation" onClick={async()=>{try{await navigator.clipboard.writeText(p.citation);toast.success('Citation copied')}catch{toast.error('Clipboard unavailable. Select and copy the citation below.')}}}><Clipboard size={18}/></button></div><p>{p.citation}</p><a href={p.url} target="_blank" rel="noreferrer" className="text-link">Verify at the source <ArrowUpRight size={16}/></a></section><section><h2>Research context</h2><div className="chips">{p.tags.map(t=><span className="chip" key={t}>{t}</span>)}</div><p className="small muted">{p.relevance}% illustrative relevance. Demo scores do not measure study quality, certainty of evidence or suitability for a particular patient.</p></section></article></>}


