'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Html,Line} from '@react-three/drei';
import {Suspense,useEffect,useMemo,useRef,useState,Component,type ReactNode} from 'react';
import * as THREE from 'three';
import {trends} from '@/data/demo';
import {readState} from '@/services';
function useMotion(){const [reduced,setReduced]=useState(false);useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches||readState().reducedMotion);update();media.addEventListener('change',update);window.addEventListener('medintel-change',update);return()=>{media.removeEventListener('change',update);window.removeEventListener('medintel-change',update)}},[]);return reduced}
const names=['CASE','SYMPTOMS','LABS','IMAGING','DISEASES','RESEARCH','SIMILAR CASES','TRENDS'];
const positions: [number,number,number][]=[[0,0,0],[-1.8,1,.2],[1.7,.85,.4],[1.75,-.75,-.3],[-1.6,-.9,.4],[.3,1.65,-.5],[-.4,-1.6,-.3],[0,.3,1.9]];
class Boundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
function Focus({point}:{point:[number,number,number]|null}){const {camera}=useThree();const target=useRef(new THREE.Vector3(0,0,6.6));useEffect(()=>{target.current.set(point?point[0]*.4:0,point?point[1]*.4:0,point?5.4:6.6)},[point]);useFrame((_,delta)=>camera.position.lerp(target.current,Math.min(delta*2,1)));return null}
function NetworkScene({selected,onSelect,reduced,labels}:{selected:number;onSelect:(i:number)=>void;reduced:boolean;labels:string[]}){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{if(ref.current&&!reduced)ref.current.rotation.y=Math.sin(clock.elapsedTime*.12)*.15});return <><ambientLight intensity={1.8}/><directionalLight position={[3,4,5]} intensity={3} color="#ffffff"/><pointLight position={[-3,-2,3]} color="#9b9edf" intensity={14}/><group ref={ref}>{positions.slice(1).map((p,i)=><Line key={i} points={[[0,0,0],p]} color={selected===i+1?'#6d78ad':'#a9b3cb'} transparent opacity={.55} lineWidth={selected===i+1?2:1}/>)}{positions.map((p,i)=><group key={labels[i]} position={p}><mesh onClick={e=>{e.stopPropagation();onSelect(i)}} scale={selected===i?1.15:1}><sphereGeometry args={[i===0?.9:.18,40,24]}/><meshPhysicalMaterial color={i===0?'#ccd6e9':selected===i?'#8e93bc':'#c2c5df'} transparent opacity={i===0?.6:.93} roughness={.15} metalness={.13} clearcoat={1}/></mesh>{i===0&&<mesh><sphereGeometry args={[.91,18,12]}/><meshBasicMaterial color="#9daacc" wireframe transparent opacity={.13}/></mesh>}<Html position={[0,i===0?0:.34,0]} center><button className={'node-label '+(selected===i?'selected':'')} onClick={()=>onSelect(i)}>{labels[i]}</button></Html></group>)}</group><Focus point={selected?positions[selected]:null}/><OrbitControls enablePan={false} enableZoom={false} enableRotate={false}/></>}
export function ClinicalIntelligenceModel({onSelect,compact=false,activeIndex,labels=names}:{onSelect?:(name:string,index:number)=>void;compact?:boolean;activeIndex?:number;labels?:string[]}){const [selected,setSelected]=useState(0);const reduced=useMotion();const [ready,setReady]=useState(false);useEffect(()=>{setReady(true)},[]);useEffect(()=>{if(activeIndex!==undefined)setSelected(activeIndex)},[activeIndex]);const choose=(i:number)=>{setSelected(i);onSelect?.(labels[i],i)};const fallback=<div className="model-fallback">{labels.map((n,i)=><button className="chip" key={n} onClick={()=>choose(i)}>{n}</button>)}</div>;return <div className={'model '+(compact?'compact':'')} aria-label="Interactive clinical evidence network">{ready?<Boundary fallback={fallback}><Canvas dpr={[1,1.5]} camera={{position:[0,0,6.6],fov:43}} gl={{alpha:true,antialias:true,powerPreference:'low-power'}}><Suspense fallback={null}><NetworkScene selected={selected} onSelect={choose} reduced={reduced} labels={labels}/></Suspense></Canvas></Boundary>:fallback}</div>}
const xyz=(lat:number,lon:number,r=1.75):[number,number,number]=>{const phi=(90-lat)*Math.PI/180,theta=(lon+180)*Math.PI/180;return [-r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta)]};
function GlobeScene({selected,onSelect,reduced}:{selected:string;onSelect:(id:string)=>void;reduced:boolean}){const [rings,setRings]=useState<number[][][]>([]);useEffect(()=>{fetch('/land.geojson').then(r=>r.json()).then((data:any)=>setRings(data.features.flatMap((f:{geometry:{type:string;coordinates:number[][][]|number[][][][]}})=>f.geometry.type==='Polygon'?f.geometry.coordinates:(f.geometry.coordinates as number[][][][]).flat()))).catch(()=>{})},[]);const grid=useMemo(()=>{const lines:[number,number,number][][]=[];for(let lat=-60;lat<=60;lat+=30)lines.push(Array.from({length:73},(_,i)=>xyz(lat,i*5-180)));for(let lon=-180;lon<180;lon+=30)lines.push(Array.from({length:37},(_,i)=>xyz(i*5-90,lon)));return lines},[]);return <><ambientLight intensity={2}/><directionalLight position={[4,4,6]} intensity={2}/><mesh><sphereGeometry args={[1.73,64,40]}/><meshStandardMaterial color="#e1e8ea" roughness={.68}/></mesh>{grid.map((points,i)=><Line key={i} points={points} color="#a9b8bd" lineWidth={.6} transparent opacity={.45}/>)}{rings.map((ring,i)=><Line key={'land'+i} points={ring.map(([lon,lat])=>xyz(lat,lon,1.76))} color="#95aaa9" lineWidth={1.2}/>)}{trends.map(t=><group key={t.id} position={xyz(t.lat,t.lon,1.8)}><mesh onClick={e=>{e.stopPropagation();onSelect(t.id)}}><sphereGeometry args={[t.id===selected?.075:.045,16,12]}/><meshBasicMaterial color={t.id===selected?'#6d639a':'#8b91b4'}/></mesh><Html center distanceFactor={8} occlude position={[0,.13,0]}><button className={'globe-label '+(t.id===selected?'selected':'')} onClick={()=>onSelect(t.id)}>{t.region}</button></Html></group>)}<OrbitControls enablePan={false} minDistance={3.2} maxDistance={8} autoRotate={!reduced} autoRotateSpeed={.35}/></>}
export function DiseaseGlobe({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}){const [ready,setReady]=useState(false);const reduced=useMotion();useEffect(()=>{setReady(true)},[]);const fallback=<div className="model-fallback">{trends.map(t=><button className="chip" onClick={()=>onSelect(t.id)} key={t.id}>{t.region}</button>)}</div>;return <div className="globe" aria-label="Interactive globe. Drag to rotate, scroll to zoom. Regions also available below.">{ready?<Boundary fallback={fallback}><Canvas camera={{position:[3,1.8,4.5],fov:43}} dpr={[1,1.5]}><Suspense fallback={null}><GlobeScene selected={selected} onSelect={onSelect} reduced={reduced}/></Suspense></Canvas></Boundary>:fallback}</div>}

